### ISSUE TITLE
Create icon set for Theme 1

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/ux#10]
Goal: Replace EUI glyphs, logos and icons with redesigned versions for OUI. The outcome should result in non-jarring change to the user experience while expressing the OpenSearch brand.

Research:
- [ ] [Glyps/Icons - Replacements, Additions & Naming Research Spike](https://github.com/opensearch-project/oui/issues/32)

Tasks: 
**PHASE 1**

- [ ] [Determine execution approach to OUI 1.x glyphs ](https://github.com/opensearch-project/ux/issues/12)
- [ ] [Help](https://github.com/opensearch-project/ux/issues/11)
- [ ] [Save](https://github.com/opensearch-project/ux/issues/13)
- [ ] [Timeline](https://github.com/opensearch-project/ux/issues/14)
- [ ] Deprecate Timelion glyph and replace instances with Timeline glyph (Engineering)
