### ISSUE TITLE
[META] Make Point in Times Available in Dashboards

### ISSUE THREAD

**Issue by shanilpa** [opensearch-project/ux#61]
## Context
This is a meta issue for UX work/tasks related to making Point in Times (PITs) available in OpenSearch Dashboards.

## UX Scope
The scope of this UX work focuses around these high level use cases:

- [ ] Allow users to view and manage PIT objects from single data sources
- [ ] Allow users to get details on a PIT
- [ ] Allow users to create a PIT
- [ ] Allow users to edit an existing PIT
- [ ] Allow users to use a PIT in Discover
