### ISSUE TITLE
[META] OpenSearch Dashboards augmentations with plugin objects

### ISSUE THREAD

**Issue by xeniatup** [opensearch-project/ux#66]
## Context
This is a meta issue for UX work related to making plugin objects available in OpenSearch Dashboards.

## User flows

- [ ] https://github.com/opensearch-project/alerting-dashboards-plugin/issues/483
- [ ] https://github.com/opensearch-project/alerting-dashboards-plugin/issues/484
- [ ] https://github.com/opensearch-project/alerting-dashboards-plugin/issues/485
- [ ] https://github.com/opensearch-project/alerting-dashboards-plugin/issues/486
